### ISSUE TITLE
Plugin not loading?

### ISSUE THREAD

**Issue by jordanh** [metabase/sudoku-driver#1]
Hi there! Very exciting you're going through the arduous job of documenting this interface. Equally excited to dig in and write a driver.

I am having a bit of trouble getting this plugin to load. I've done the following:

1. (from this repo) `lein clean && DEBUG=1 LEIN_SNAPSHOTS_IN_RELEASE=true lein uberjar`
2. `cp target/uberjar/sudoku.metabase-driver.jar ~/opt/metabase/plugins/`
3. `cd ~/opt/metabase ; java -jar metabase.jar`

When I navigate to: http://localhost:3000/admin/databases/create I don't see the database as an option...is there a trick to getting metabase to load the jars from the plugin directory?

**Comment by dacort** [comment]
The new driver plugin system ([#9087](https://github.com/metabase/metabase/pull/9087)) is part of the next version of Metabase (0.32). So you'll need to snag the source and build your own jar.

See https://github.com/metabase/metabase/blob/master/docs/developers-guide.md for more details.

If it works, you should see log messages similar to the following:
```
INFO plugins.lazy-loaded-driver :: Registering lazy loading driver :sudoku...
INFO metabase.driver :: Registered driver :sudoku  🚚
```

**Comment by jordanh** [comment]
This was helpful! Took me a bit to get back to this but it allowed the `v0.32` release to make it out in the wild as an official Docker container. I am able to load the sudoku driver by mapping a local directory containing the plugin's jar file:

```bash
$ docker run -p 3001:3000 -v /Users/jordanhusney/opt/metabase/plugins/:/app/plugins2 -e MB_PLUGINS_DIR=/app/plugins2 --name metabase metabase/metabase
```
