### ISSUE TITLE
metabase expect absolute paths relative paths defined in deps.edn

### ISSUE THREAD

**Issue by robstoll** [metabase/sudoku-driver#5]
if you run `clojure -X:dev:build` then you run into the following issue:
```
Step failed: Assert failed: All dirs should be absolute, got: ["./src" "./resources"]
(every? u/absolute? dirs)
```

**Comment by dpsutton** [comment]
I've given a workaround in https://github.com/metabase/sudoku-driver/pull/6 . A better fix will take a bit of work on the metabase side unfortunately.
